## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,2021-07-20 23:07:45,-46.6000,168.3333,43.81,75,100,10.38,light rain
1,1,Ribeira Grande,PT,2021-07-20 23:07:14,38.5167,-28.7000,68.72,87,22,14.25,few clouds
2,2,Kodiak,US,2021-07-20 23:03:33,57.7900,-152.4072,54.75,93,100,8.05,overcast clouds
3,3,Castro,BR,2021-07-20 23:08:19,-24.7911,-50.0119,44.94,65,95,1.68,overcast clouds
4,4,Kysyl-Syr,RU,2021-07-20 23:08:23,63.8986,122.7617,58.44,94,100,4.88,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("Enter min temp: "))
max_temp = float(input("Enter max temp: "))

Enter min temp: 60
Enter max temp: 80

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= 60) 
                                       & (city_data_df["Max Temp"] <= 80)]
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Ribeira Grande,PT,2021-07-20 23:07:14,38.5167,-28.7000,68.72,87,22,14.25,few clouds
6,6,Praia Da Vitoria,PT,2021-07-20 23:08:23,38.7333,-27.0667,70.75,89,42,13.38,scattered clouds
7,7,Rikitea,PF,2021-07-20 23:08:13,-23.1203,-134.9692,71.24,65,99,24.96,overcast clouds
11,11,Sutto,HU,2021-07-20 23:08:24,47.7589,18.4487,65.03,72,18,6.06,few clouds
12,12,Atuona,PF,2021-07-20 23:03:29,-9.8000,-139.0333,77.40,75,38,26.11,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Date                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna(how="any")
clean_df.isnull().sum()

City_ID                0
City                   0
Country                0
Date                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Ribeira Grande,PT,68.72,few clouds,38.5167,-28.7000,
6,Praia Da Vitoria,PT,70.75,scattered clouds,38.7333,-27.0667,
7,Rikitea,PF,71.24,overcast clouds,-23.1203,-134.9692,
11,Sutto,HU,65.03,few clouds,47.7589,18.4487,
12,Atuona,PF,77.40,scattered clouds,-9.8000,-139.0333,
14,Bengkulu,ID,74.46,broken clouds,-3.8004,102.2655,
16,Envira,BR,75.02,few clouds,-7.3000,-70.2167,
17,Azad Shahr,IR,72.12,clear sky,34.7909,48.5707,
23,Amahai,ID,77.70,broken clouds,-3.3333,128.9167,
24,Jamestown,US,77.29,clear sky,42.0970,-79.2353,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        hotels = hotels["results"][0]["name"]
        print(hotels)
    except (IndexError):
        print("Hotel not found...skipping.")

Quinta da Meia Eira
Hotel Branco I
People ThankYou
Piszke Vendégház
Villa Enata
Grage Hotel Bengkulu
Hotel not found...skipping.
مزارحاج علی ربانی
HOTEL ISABELA
Hampton Inn & Suites Jamestown
Comfort Inn
Hotel Chik Chik Namibe
GreenTree Inn Linxia Autonomous Prefecture Linxia Oxford River Avenue Express Hotel
Hotel Du Lac
Paradise Inn & Suites
Hotel Olako
Select Inn
Pousada Porto Praia
Gostinitsa
Hotel not found...skipping.
Tara Hotel
Keleti Beach Resort
Apartamento de Kaio.
Goto Guesthouse Utojuku & SA Car Rental
Veranda Paul et Virginie Hotel & Spa
Pousada Porto De Canoas
Parkside Inn
Gîte kajeon
Hotel Syariah CN Darussalam
The Explorer Hotel
Hotel not found...skipping.
Dena Hotel
Bora-Bora Pearl Beach Resort & Spa
Pousada dos Navegantes
End of The Road Ltd.
Aviador Hotel Boutique
Kost Pria
Hotel Santika Luwuk
Pestana Bahia Praia
Casa Laguna, Bed & Breakfast
Pension Feldgärtenhof
Hôtel Matagami
Mawell Resort
Derogongan Residence
Broadwater Mariner Resort
HOSPEDAJE XIMENA
Finch Bay Galapagos Hotel
محمد هادي ال فطيح
Hotel Ust-Nera
Lindi paradise house
Casona Del Muelle
Alarne - Área De Lazer Do Alto Rio Negro
متنزه و بحيرة سيان
7Days Inn Qinhuangdao Changli Jieyang Street
Rouba Residency
INN NEW HORIZON
Birjand Tourist Hotel
Thank Inn Chain Hotel gansu wuwei liangzhou district xiguan middle road
Durrant House Hotel
Hotel not found...skipping.
Hotel Santa Maria
Curubo Hotel
Maitai Lapita Village Huahine
Aridolf Resort Wellness and Spa
Jiabin Inn
Hotel Park
Hotel not found...skipping.
Hotel not found...skipping.
Windy Lodge & Beach Resort
Posada Villaven C.A.
The Hotel Petropavlovsky
JABIR HOTEL
Hotel not found...skipping.
DIGNITY GUEST (RUGAIMUKAMU)
Le Diamant De Mireille
La Ode Husein
Debright Motel
Northland Motor Hotel
Elizaveta Shevchuk's House
Estancia Hotel - Jardim MS
Rio Xingu Camping
Hotel not found...skipping.
Mishan Hotel
مقبرة ال مجمل
Pousada Maria Bonita
Gostinitsa Tsentral'naya
la Tour des Anglais
Conrad Bora Bora Nui
Sulthan Hotel International
Ramah Kost KITA
Matu Island
Hotel not found...skipping.
The Sternwheeler Hotel & Conference Centre
LT Aparthotel
Hotel do Campo
Hotel La Montaña
Hotel not found...skipping.
Hotel 77 Poso
Gallows Cove
Abbott's Bed & Breakfast
Hotel IK Residency
Chambres d'hôte "La Trinité"
Foyer ADM
Hospitality Carnarvon
Gostinitsa
Hotel not found...skipping.
Casa Das Faias
Alenat Tsentr
Hotel Den Helder
Hotel Gabbiano
Complexo Sonho Real
Valle Aridane
Süleyman Tez Ev
Holiday Inn Express Dryden, an IHG Hotel
Wahyu
El Medina
Pasportnyy Stol
SEGAYA PROPERTY
Floresta Amazonica Hotel
Hôtel Mantis
La casa de Roberto
New Pammawaddy Hotel
Pazo de Verdes
Shandrani Beachcomber Resort & Spa
Kingfish Westcoast Adventures Ltd. Kitimat Estuary Lodge B&B
ฟาร์มแพะ หนองผักหนาม
Pinghu Hostel
Shwe Phyu Hotel
Pudong Holiday Hotel
奄美ポートタワーホテル
Hawaii Hotel
Westmark Sitka
Pousada Morro Dos Ventos
Fengshui Residence
Airport Lodge Kiunga
Vila Nova Hotel
Agan-Hotel
Petit Hotel Hostatgeria Sant Salvador
Mercure Padang
Sai Deluxe Shahapur
Bow Manor Motor Hotel
Moosonee Lilypad
Maqna Hotel by Prasanthi
Casa Mika Ciobanus
Don Eddie's Sport Fishing Center
Hotel not found...skipping.
Grape Sightseeing Garden
Knobby's Fly-In Camps
Crôa Mares Hotel
Hotel Villa Kitzia Huacho
Hotel not found...skipping.
Империя
Reserva do Abiaí
The Fort Nelson Hotel
ibis Styles Karratha
Hotel Star inn Peniche
Hotel Xaguate
Paradise Court
Quality Hotel & Suites
7Days Inn Chongqing Shiqiaopu
Pesanggrahan Garam
Hotel San Isidro Oficial
Pryvatna Sadyba
Casa Tia Villa
Gran Pajaten Trek
Hampton Inn & Suites West Bend
Laoyutang Resort
Hotel John
Кочевник
Beluga Lake Lodge
Hotel not found...skipping.
Hotel e Restaurante Aҫai
Motel des voyageurs
Sunrise Attitude Hotel
Hôtel Opémiska
Niamat parda Center chaman
Urban Style by Front One
Cattleman's Rest Motor Inn
Shanti Maurice Resort & Spa
Posada Llovizna Rodríguez
Casa Maquia
Yunhe Star Hotel
Hotel not found...skipping.
Iroha-ya Inn
Hôtel Britannique - Paris Centre
Atlantic Oceanside Hotel & Event Center
Hotel not found...skipping.
Penginapan Kim
hotêl doufoulougou
Hotel not found...skipping.
castelo pizzaria
Screensaver
Puri Brata
Hotel not found...skipping.
Iberostar Founty Beach
Companion
Au Doc Motel
Casa Morey Hotel & Restaurant
Ha'apai Beach Resort
Ming Yang Inn
Yingbin Restaurant
Gostinitsa Tommot
Hotel not found...skipping.
The West Cork Hotel
Hotel not found...skipping.
GreenTree Hotel Rongcheng Bus Station
Marine Club Beach Resort
Hotel Porto Santo & Spa
Villa Veronica Resort Private Pool
Wingate By Wyndham Rome
Apartment Av. Castelao
Hotel Flôr de Sal
Hotel not found...skipping.
Longmenkezhan
Hotel not found...skipping.
ibis budget Newport
Orbita Boutique Hotel
Gulisitan Hotel
Shuncheng Hotel
The Hamsa Resort
Xinya International Hotel
Hotel Mansión
The Esplanade Hotel
Aracati Hotel
Quinta Splendida Wellness & Botanical Garden
Zambeze Paraíso Misterioso
Baranof Downtown, Bw Signature Collection
Aston Pontianak Hotel & Convention Center
زلطن الشرقية
Hotel Surya Palace
Hotel Conceição
TDC Village (Hundred Man Camp)
ibis Calais Car Ferry
Hotel Campestre La Contea
Aipana Plaza Hotel
Amiin Hotel
Hotel New Green View
Hotel Rajshree
Hotel Castrum Villae by Walk Hotels
Hôtel & Restaurant DIANA Ambilobe
Vanderhoof Inn
Groote Eylandt Lodge
Kemalpaşa Öğretmen Evi
Bella Vista Palace Hotel
Madame Vacances - Résidence Les Consuls de la Mer
Guangyuan Poetry Hotel
The Blue Sky Hotel and Tower
Hotel Curuça
Airport Inn
Best Western Arena Hotell
Hotel Maria
Black Rock Oceanfront Resort
Ujamaa Beach Resort
Hotel not found...skipping.
Nemegosenda Lake Lodge
Otel' Perekrestok
Hotel not found...skipping.
Hotel not found...skipping.
Bloc D tazoumbirt (amar)
Hotel not found...skipping.
Le Monitel
Severnoye Siyaniye
Zori
Salinas do Maragogi All Inclusive Resort
Hotel not found...skipping.
Grand Hotel Cirta
Vienna 3 Best Hotel Sheyang Jiefang Rd
Hôtel Raiatea Lodge
Hvide Sande Hotel
Hotel not found...skipping.
Junyu Tiancheng Hotel
Individual'nyy Predprinimatel' Rakhmanin Andrey Aleksandrovich
Fort Johnstone Hotel
Căminul școlii profesionale
Harmony Inn
Quinta das Giestas
Ananda Lodge
Elwiras B&B
Galaxy Grand Hotel
Villa Park Hotel | Natal
Ka Waboana Lodge
Pousada Monte Carmelo O Pão
Tarumã Tropical Hotel
Quality Suites Vila Velha
Marystown Hotel & Convention Centre
Safari Mashariki Lodge
Hotel Náutico de Paita
Aspen Extended Stay Suites
Hotel Khovd
Hotel not found...skipping.
Fuente del Guania Hotel de Lujo
Snows Cove Lodge
Hotel not found...skipping.
Springfields Hotel
Gostinitsa "Shvedka"
Hotel Salayish | ሆቴል ሳላይሽ
Baltica Pension
Hotel Samari
Hotel not found...skipping.
Colinas de Matasiete
Hotel El Barcon
Pereybere Hotel & Spa
محمدالمبروك الاريقط
"Plantation Bed and Breakfast
Les Jardins de la Mer Ghar el Melh
Josilene Castro
Hotel not found...skipping.
Voi Wildlife Lodge
Hospedaje Costa Bella
Уязы-Тау гостиница
Hotel not found...skipping.
Bonthe Holiday Village
STARiHOTELS Nilanagar Solapur
Okhotsk Palace Hotel
Sandton Hotel Kasese
Wingate by Wyndham Regina
IU Hotel Jinzhong Yuhua Road
Pin Drop Hotel
Apartment on Zvereva
Hotel Fellip
Boyue boutique Hotel
Hotel Conde del Jaral
Hotel "Central"
ibis Bonn
Hotel not found...skipping.
OlusHome
Hotel not found...skipping.
Hotel not found...skipping.
My home
சல்லிக்கோடாங்கிபட்டி
Hotel Nemuro Kaiyoutei
Hôtel Abda
Actons Hotel Kinsale
Brisas del Yucao
L l ganeshkar
Stonewall Inn
Dali Travelling With Hostel
Hotel Full Business
Hotel Nusantara Nabire
Guest Hôtel

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df["Hotel Name"].replace('', np.nan, inplace=True)
hotel_df.dropna(subset=["Hotel Name"], inplace=True)
clean_hotel_df = hotel_df.copy()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Ribeira Grande,PT,68.72,few clouds,38.5167,-28.7000,Quinta da Meia Eira
6,Praia Da Vitoria,PT,70.75,scattered clouds,38.7333,-27.0667,Hotel Branco I
7,Rikitea,PF,71.24,overcast clouds,-23.1203,-134.9692,People ThankYou
11,Sutto,HU,65.03,few clouds,47.7589,18.4487,Piszke Vendégház
12,Atuona,PF,77.40,scattered clouds,-9.8000,-139.0333,Villa Enata
14,Bengkulu,ID,74.46,broken clouds,-3.8004,102.2655,Grage Hotel Bengkulu
17,Azad Shahr,IR,72.12,clear sky,34.7909,48.5707,مزارحاج علی ربانی
23,Amahai,ID,77.70,broken clouds,-3.3333,128.9167,HOTEL ISABELA
24,Jamestown,US,77.29,clear sky,42.0970,-79.2353,Hampton Inn & Suites Jamestown
25,Sept-Iles,CA,65.25,scattered clouds,50.2001,-66.3821,Comfort Inn

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))